<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>

<div id="addthis_wrap">

    <div class="addthis_toolbox addthis_default_style ">
        <a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
        <iframe allowtransparency="true" frameborder="0" scrolling="no"
                src="https://platform.twitter.com/widgets/tweet_button.html"
                style="width:95px; height:20px; float:left;"></iframe>
        <a class="addthis_button_pinterest_pinit" pi:pinit:layout="horizontal"></a>
        <a class="addthis_counter addthis_pill_style"></a>
    </div>
    <script type="text/javascript">var addthis_config = {"data_track_addressbar": false};</script>

    <script type="text/javascript"
            src="http://s7.addthis.com/js/300/addthis_widget.js#pubid=ra-529be2200cc72db5"></script>

</div>