<?php


/**
 * Product list template
 *
 * @var $block \Gym\JsAuth\Block\Adminhtml\Auth
 */
?>
<div class="row">
    <div class="col-10">
        <div class="card">
            <div class="card-header" id="video-header-card">
                Video
            </div>
            <div class="card-body">
                <video id="main-video" autoplay muted></video>
            </div>
            <div class="card-footer">
                <button type="button" class="btn btn-success btn-lg btn-block" data-action="toggleRecognition">Iniciar reconocimiento</button>
            </div>
        </div>

    </div>
    <div class="col-2">
        <div class="card" style="width: 18rem;">
            <img class="card-img-top" src="..." alt="Card image cap" id="person-image">
            <div class="card-body">
                <h5 class="card-title" id="person-name">Desconocido</h5>
            </div>
            <ul class="list-group list-group-flush">
                <li class="list-group-item"><strong>CI:</strong><span id="person-ci"></span></li>
                <li class="list-group-item"><strong>Email:</strong><span id="person-email"></span></li>
            </ul>
            <div class="card-body">
                <button type="button" class="btn btn-success btn-lg btn-block" data-action="AccessRegister">Registrar Acceso</button>
            </div>
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "jsAuth": {
                "assetBaseUrl" : "<?= $block->getAdminBaseUrl() ?>",
                "luxandApiUrl" : "<?= $block->getApiUrl() ?>",
                "luxandToken" : "<?= $block->getApiToken() ?>"
                }
        }
    }
</script>
