<?php
/**
 * Product list template
 *
 * @var $block \Gym\JsAuth\Block\Adminhtml\Auth
 */
?>

<div class="row" id="appvue">
    <div class="col-12">
        <div :class="'alert alert-' + info.type" role="alert">
            <div v-if="info.showSpinner" class="spinner-grow" role="status">
            </div>  {{ info.msg }}
        </div>
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-body">
                <video id="main-video" autoplay muted></video>
            </div>
            <div class="card-footer">
                <button 
                    :disabled="isProcessing" 
                    type="button" 
                    class="btn btn-success btn-lg btn-block"
                    v-on:click="initFaceDetection"
                    >Iniciar reconocimiento</button>
            </div>
        </div>

    </div>
    <div class="col-4">
        <div class="card card-user-info" v-if="isSucessfullyIdentify">
            <img class="card-img-top" v-bind:src="'data:image/png;base64,' + identifiedPerson.image64" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title card-user-name">{{ identifiedPerson.name }}</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <span>{{ identifiedPerson.email }}</span>
                        </li>
                        <li class="list-group-item">
                            <strong>CI:</strong>
                            <span>{{ identifiedPerson.ci }}</span>
                        </li>
                </ul>
            </div>
            <div class="card-footer">
                <button 
                    :disabled="isProcessing"  
                    type="button" 
                    v-on:click="accessRegister"
                    class="btn btn-success btn-lg btn-block"
                    >Registrar Acceso</button>
                    <button 
                    :disabled="isProcessing"  
                    type="button" 
                    v-on:click="resetValues"
                    class="btn btn-danger btn-lg btn-block"
                    >Ocultar</button>
            </div>
            
        </div>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "jsAuth": {
                "assetBaseUrl" : "<?= $block->getAdminBaseUrl() ?>",
                "luxandApiUrl" : "<?= $block->getApiUrl() ?>",
                "luxandToken" : "<?= $block->getApiToken() ?>",
                "registerUrl" : "<?= $block->getUrlRegistry() ?>"
                }
        }
    }
</script>
