<?php
/**
 *
 * SM Listing Tabs - Version 2.5.0
 * Copyright (c) 2017 YouTech Company. All Rights Reserved.
 * @license - Copyrighted Commercial Software
 * Author: YouTech Company
 * Websites: http://www.magentech.com
 */

use Magento\Framework\App\Action\Action;

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
if ($this->_isAjax()) {
    $products = $this->_ajaxLoad();
    $config   = $this->_getConfig();
} else {
    $config   = $this->getData('config');
    $products = $this->getData('products');
}
$_helper = $this->helper('Magento\Catalog\Helper\Output');

$viewMode        = 'grid';
$image           = 'category_page_grid';
$imageBig        = 'category_page_grid_big';
$showDescription = false;
$templateType    = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
$type_loadmore   = $config['type_show'] == 'loadmore' ? true : false;
$cls_mark        = $type_loadmore ? ' ltabs-mark ' : '';

$_config      = $this->helper('Sm\Market\Helper\Data');
$homeStyle    = $_config->getThemeLayout('home_style');
$nb_type_show = $config['type_show'];
$lthelper     = $this->helper('Sm\ListingTabs\Helper\Data');
$nb_rows      = 5;
$i            = 0;
$count        = 0;
$count_item   = count($products);
/**
 * Position for actions regarding image size changing in vde if needed
 */
$pos = $block->getPositioned();
if (count($products)) {
    ?>
    <div class="<?php /* @escapeNotVerified */
    echo $viewMode; ?> products-<?php /* @escapeNotVerified */
    echo $viewMode; ?>">
        <?php $iterator = 1; ?>
        <div class="products list items product-items  <?php echo $type_loadmore == false ? ' owl-carousel ' : ''; ?>" <?php echo $type_loadmore ? 'data-liffect="fadeIn"' : ''; ?>>
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($products as $_product):
                $i++;
                $count++;
                ?>
                <?php if ($count % $nb_rows == 1 || $nb_rows == 1) { ?>
                <div class="item-col item">
                <div class="row">
            <?php } ?>


                <?php if ($i == 3) { ?>
                <div class="col-lg-6 product-center">
                    <?php
                    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                    $product       = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                    $images        = $product->getMediaGalleryImages();
                    $productInfo   = "product_" . rand() . time();;
                    ?>
                    <div class="item product-item <?php echo $productInfo; ?>">
                        <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */
                        $viewMode ?>">
                            <?php
                            $productImage = $block->getImage($_product, $imageBig);
                            if ($pos != null) {
                                $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                    . 'top:' . $productImage->getHeight() . 'px;"';
                            }
                            ?>
                            <?php // Product Image ?>
                            <div class="box-image">
                                <a href="<?= /* @escapeNotVerified */
                                $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                                    <?= $productImage->toHtml() ?>
                                </a>
                            </div>

                            <!--LABEL PRODUCT-->
                            <?php
                            $orgprice = (float)$_product->getPrice();
                            $fnPrice  = (float)$_product->getFinalPrice();

                            if ($_config->getAdvanced('show_salelabel')) {
                                if ($fnPrice < $orgprice) { ?>
                                    <div class="label-product label-sale">
								<span class="sale-product-icon">
									<?php echo __('Sale'); ?>
								</span>
                                    </div>
                                <?php }
                            }
                            ?>

                            <?php
                            $now      = date("Y-m-d");
                            $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                            $newsTo   = substr($_product->getNewsToDate(), 0, 10);


                            if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
                                if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                    <div class="label-product label-new">
                                        <span class="new-product-icon"><?php echo __('New'); ?></span>
                                    </div>
                                <?php }
                            } ?>
                            <!--END LABEL PRODUCT-->

                            <div class="product details product-item-details">
                                <?php
                                $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                                ?>
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       href="<?= /* @escapeNotVerified */
                                       $_product->getProductUrl() ?>">
                                        <?= /* @escapeNotVerified */
                                        $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                    </a>
                                </strong>
                                <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                                <?= /* @escapeNotVerified */
                                $block->getProductPrice($_product) ?>
                                <?= $block->getProductDetailsHtml($_product) ?>

                                <?php
                                if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                                    $specialToDate = $_product->getSpecialToDate();
                                    ?>
                                    <div class="deals-countdown"
                                         data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                                        <div class="deals-time time-day">
                                            <div class="num-time"></div>
                                            <div class="title-time"></div>
                                        </div>
                                        <div class="deals-time time-hours">
                                            <div class="num-time"></div>
                                            <div class="title-time"></div>
                                        </div>
                                        <div class="deals-time time-mins">
                                            <div class="num-time"></div>
                                            <div class="title-time"></div>
                                        </div>
                                        <div class="deals-time time-secs">
                                            <div class="num-time"></div>
                                            <div class="title-time"></div>
                                        </div>
                                    </div>
                                <?php } ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                        <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                            <?php if ($_product->isSaleable()): ?>
                                                <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                                <form data-role="tocart-form"
                                                      data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                      action="<?= /* @NoEscape */
                                                      $postParams['action'] ?>" method="post">
                                                    <input type="hidden" name="product"
                                                           value="<?= /* @escapeNotVerified */
                                                           $postParams['data']['product'] ?>">
                                                    <input type="hidden" name="<?= /* @escapeNotVerified */
                                                    Action::PARAM_NAME_URL_ENCODED ?>"
                                                           value="<?= /* @escapeNotVerified */
                                                           $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                    <?= $block->getBlockHtml('formkey') ?>
                                                    <button type="submit"
                                                            title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                            class="action tocart primary">
													<span><?= /* @escapeNotVerified */
                                                        __('Add to Cart') ?></span>
                                                    </button>
                                                </form>
                                            <?php else: ?>
                                                <?php if ($_product->isAvailable()): ?>
                                                    <div class="stock available"><span><?= /* @escapeNotVerified */
                                                            __('In stock') ?></span></div>
                                                <?php else: ?>
                                                    <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                            __('Out of stock') ?></span></div>
                                                <?php endif; ?>
                                            <?php endif; ?>
                                        </div>
                                        <div data-role="add-to-links"
                                             class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                            <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#" class="action towishlist"
                                                       title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $block->getAddToWishlistParams($_product); ?>'
                                                       data-action="add-to-wishlist" role="button">
															<span><?php /* @escapeNotVerified */
                                                                echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php } ?>

                                            <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                                                <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                <a href="#" class="action tocompare"
                                                   title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */
                                                   echo $compareHelper->getPostDataParams($_product); ?>' role="button">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Compare') ?></span>
                                                </a>
                                            <?php } ?>
                                        </div>
                                    </div>
                                    <?php if ($showDescription): ?>
                                        <div class="product description product-item-description">
                                            <?= /* @escapeNotVerified */
                                            $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                            <a href="<?= /* @escapeNotVerified */
                                            $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */
                                            $_productNameStripped ?>"
                                               class="action more"><?= /* @escapeNotVerified */
                                                __('Learn More') ?></a>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>

                            <div class="thumbs-product">
                                <?php
                                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
                                $product       = $objectManager->create('Magento\Catalog\Model\Product')->load($_product->getId());
                                $images        = $product->getMediaGalleryImages();
                                $limit         = 0;

                                foreach ($images as $child) {
                                    $limit++;
                                    //var_dump($child->getData('file'));die('123123');
                                    if ($limit <= 4) {
                                        $img = $lthelper->_getImageThumbnail($child->getData('file'));
                                        if (!empty($img) && isset($img[0])) {
                                            $big_image_config   = [
                                                'width' => 500,
                                                'height' => 500,
                                                'background' => '#ffffff',
                                                'function' => 1
                                            ];
                                            $small_image_config = [
                                                'width' => 80,
                                                'height' => 80,
                                                'background' => '#ffffff',
                                                'function' => 1
                                            ];
                                            $resizedImageBig    = $lthelper->_resizeImage($img[0], $big_image_config, 'product');
                                            $resizedImageUrl    = $lthelper->_resizeImage($img[0], $small_image_config, 'product'); ?>
                                            <div class="item-img" data-src="<?php echo $resizedImageBig; ?>">
                                                <img src="<?php echo $resizedImageUrl; ?>" alt="image"/>

                                            </div>
                                            <?php
                                        }
                                    }
                                } ?>
                            </div>

                            <script type="text/javascript">
                                require([
                                    'jquery'
                                ], function ($) {
                                    $(".<?php echo $productInfo;?> .thumbs-product .item-img").click(function () {
                                        $(".<?php echo $productInfo;?> .thumbs-product .item-img").removeClass('thumb-active');
                                        $(this).addClass('thumb-active');
                                        var thumb_src = $(this).attr("data-src");
                                        $(".<?php echo $productInfo;?> .box-image a img").attr("src", thumb_src);
                                    });
                                });
                            </script>
                        </div>
                    </div>
                </div>
            <?php } else { ?>
                <?php if (($i % 2 != 0 && $i != 5) || $i == 4) { ?>
                    <div class="col-lg-3 product-col">
                <?php } ?>
                <div class="item product-item">
                    <div class="product-item-info" data-container="product-<?= /* @escapeNotVerified */
                    $viewMode ?>">
                        <?php
                        $productImage = $block->getImage($_product, $image);
                        if ($pos != null) {
                            $position = ' style="left:' . $productImage->getWidth() . 'px;'
                                . 'top:' . $productImage->getHeight() . 'px;"';
                        }
                        ?>
                        <?php // Product Image ?>
                        <a href="<?= /* @escapeNotVerified */
                        $_product->getProductUrl() ?>" class="product photo product-item-photo" tabindex="-1">
                            <?= $productImage->toHtml() ?>
                        </a>

                        <!--LABEL PRODUCT-->
                        <?php
                        $orgprice = (float)$_product->getPrice();
                        $fnPrice  = (float)$_product->getFinalPrice();

                        if ($_config->getAdvanced('show_salelabel')) {
                            if ($fnPrice < $orgprice) { ?>
                                <div class="label-product label-sale">
							<span class="sale-product-icon">
								<?php echo __('Sale'); ?>
							</span>
                                </div>
                            <?php }
                        }
                        ?>

                        <?php
                        $now      = date("Y-m-d");
                        $newsFrom = substr($_product->getNewsFromDate(), 0, 10);
                        $newsTo   = substr($_product->getNewsToDate(), 0, 10);


                        if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
                            if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                <div class="label-product label-new">
                                    <span class="new-product-icon"><?php echo __('New'); ?></span>
                                </div>
                            <?php }
                        } ?>
                        <!--END LABEL PRODUCT-->

                        <div class="product details product-item-details">
                            <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                            ?>
                            <strong class="product name product-item-name">
                                <a class="product-item-link"
                                   href="<?= /* @escapeNotVerified */
                                   $_product->getProductUrl() ?>">
                                    <?= /* @escapeNotVerified */
                                    $_helper->productAttribute($_product, $_product->getName(), 'name') ?>
                                </a>
                            </strong>
                            <?= $block->getReviewsSummaryHtml($_product, $templateType) ?>
                            <?= /* @escapeNotVerified */
                            $block->getProductPrice($_product) ?>
                            <?= $block->getProductDetailsHtml($_product) ?>

                            <?php
                            if ((int)$config['display_countdown'] && !empty($_product->getSpecialPrice()) && !empty($_product->getSpecialToDate())) {
                                $specialToDate = $_product->getSpecialToDate();
                                ?>
                                <div class="deals-countdown"
                                     data-timer="<?php echo date("Y/m/d H:i:s", strtotime($specialToDate)); ?>">
                                    <div class="deals-time time-day">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                    <div class="deals-time time-hours">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                    <div class="deals-time time-mins">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                    <div class="deals-time time-secs">
                                        <div class="num-time"></div>
                                        <div class="title-time"></div>
                                    </div>
                                </div>
                            <?php } ?>

                            <div class="product-item-inner">
                                <div class="product actions product-item-actions"<?= strpos($pos, $viewMode . '-actions') ? $position : '' ?>>
                                    <div class="actions-primary"<?= strpos($pos, $viewMode . '-primary') ? $position : '' ?>>
                                        <?php if ($_product->isSaleable()): ?>
                                            <?php $postParams = $block->getAddToCartPostParams($_product); ?>
                                            <form data-role="tocart-form"
                                                  data-product-sku="<?= $block->escapeHtml($_product->getSku()) ?>"
                                                  action="<?= /* @NoEscape */
                                                  $postParams['action'] ?>" method="post">
                                                <input type="hidden" name="product"
                                                       value="<?= /* @escapeNotVerified */
                                                       $postParams['data']['product'] ?>">
                                                <input type="hidden" name="<?= /* @escapeNotVerified */
                                                Action::PARAM_NAME_URL_ENCODED ?>"
                                                       value="<?= /* @escapeNotVerified */
                                                       $postParams['data'][Action::PARAM_NAME_URL_ENCODED] ?>">
                                                <?= $block->getBlockHtml('formkey') ?>
                                                <button type="submit"
                                                        title="<?= $block->escapeHtml(__('Add to Cart')) ?>"
                                                        class="action tocart primary">
												<span><?= /* @escapeNotVerified */
                                                    __('Add to Cart') ?></span>
                                                </button>
                                            </form>
                                        <?php else: ?>
                                            <?php if ($_product->isAvailable()): ?>
                                                <div class="stock available"><span><?= /* @escapeNotVerified */
                                                        __('In stock') ?></span></div>
                                            <?php else: ?>
                                                <div class="stock unavailable"><span><?= /* @escapeNotVerified */
                                                        __('Out of stock') ?></span></div>
                                            <?php endif; ?>
                                        <?php endif; ?>
                                    </div>
                                    <div data-role="add-to-links"
                                         class="actions-secondary"<?= strpos($pos, $viewMode . '-secondary') ? $position : '' ?>>
                                        <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                                            <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                <a href="#" class="action towishlist"
                                                   title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"
                                                   data-post='<?php /* @escapeNotVerified */
                                                   echo $block->getAddToWishlistParams($_product); ?>'
                                                   data-action="add-to-wishlist" role="button">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Wish List') ?></span>
                                                </a>
                                            <?php endif; ?>
                                        <?php } ?>

                                        <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                                            <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                            <a href="#" class="action tocompare"
                                               title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"
                                               data-post='<?php /* @escapeNotVerified */
                                               echo $compareHelper->getPostDataParams($_product); ?>' role="button">
													<span><?php /* @escapeNotVerified */
                                                        echo __('Add to Compare') ?></span>
                                            </a>
                                        <?php } ?>
                                    </div>
                                </div>
                                <?php if ($showDescription): ?>
                                    <div class="product description product-item-description">
                                        <?= /* @escapeNotVerified */
                                        $_helper->productAttribute($_product, $_product->getShortDescription(), 'short_description') ?>
                                        <a href="<?= /* @escapeNotVerified */
                                        $_product->getProductUrl() ?>" title="<?= /* @escapeNotVerified */
                                        $_productNameStripped ?>"
                                           class="action more"><?= /* @escapeNotVerified */
                                            __('Learn More') ?></a>
                                    </div>
                                <?php endif; ?>
                            </div>
                        </div>
                    </div>
                </div>

                <?php if (($i % 2 == 0 && $i != 4) || $i == 5) { ?>
                    </div>
                <?php } ?>
            <?php } ?>


                <?php if (($count % $nb_rows == 0 || $count == $count_item)) { ?>
                </div>
                </div>
                <?php $i = 0;
            } ?>
            <?php endforeach; ?>
        </div>
    </div>
<?php } else {
    if (!$this->_isAjax()) { ?>
        <div class="message info empty">
            <div><?php /* @escapeNotVerified */
                echo __('We can\'t find products matching the selection.') ?></div>
        </div>
    <?php }
} ?>