<?php $welcomeMessage = $block->getWelcome(); ?>

<div class="header-container header-style-13">
    <div class="header-top">
        <div class="container">
            <div class="row row-topheader">
                <div class="col-lg-5 col-md-4 customer-action-header">
                    <?php echo $block->getChildHtml('language-header'); ?>
                    <?php echo $block->getChildHtml('currency-header'); ?>
                </div>

                <div class="col-lg-7 col-md-8 header-top-links">
                    <?php echo $block->getChildHtml('toplinks-header'); ?>
                </div>
            </div>
        </div>
    </div>

    <div class="header-middle">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-2 logo-header">
                    <?php echo $block->getChildHtml('logo_theme'); ?>
                </div>

                <div class="col-xl-9 col-lg-10 header-middle-right">
                    <div class="middle-right-content">
                        <div class="main-megamenu">
                            <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml(); ?>
                        </div>

                        <div class="navigation-mobile-container">
                            <?php echo $block->getChildHtml('navigation.mobile'); ?>
                        </div>

                        <div class="minicart-header">
                            <div class="minicart-content">
                                <?php echo $block->getChildHtml('cart-header'); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-bottom">
        <div class="container">
            <div class="row">
                <div class="col-xl-3 col-lg-4 sidebar-megamenu">
                    <div class="megamenu-content-sidebar">
                        <div class="btn-megamenu">
                            <a href="javascript:void(0)"
                               title="<?php echo __('All Categories') ?>"><?php echo __('All Categories') ?></a>
                        </div>

                        <div class="menu-ver-content">
                            <?php
                            if ($_config->getGeneral('menu_style') == 'megamenu') {
                                echo $block->getChildHtml('navigation-header-megamenu');
                            } else {
                                echo $block->getChildHtml('navigation-header');
                            }
                            ?>
                        </div>
                    </div>
                </div>

                <div class="col-xl-9 col-lg-8 search-header-container">
                    <div class="search-header">
                        <?php echo $block->getChildHtml('search-header-pro'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<?php if ($_config->getGeneral('menu_ontop') == 1) { ?>
    <script type="text/javascript">
        require([
            'jquery'
        ], function ($) {
            $window = $(window);
            if ($('.header-bottom').length) {
                menu_offset_top = $('.header-bottom').offset().top;

                function processScroll() {
                    var scrollTop = $window.scrollTop();
                    if (scrollTop >= menu_offset_top) {
                        $('.header-bottom').addClass('menu-on-top');
                        $('body').addClass('body-on-top');
                    } else if (scrollTop <= menu_offset_top) {
                        $('.header-bottom').removeClass('menu-on-top');
                        $('body').removeClass('body-on-top');
                    }
                }

                processScroll();
                $window.scroll(function () {
                    processScroll();
                });
            }
        });
    </script>
<?php } ?>
