<?php $welcomeMessage = $block->getWelcome(); ?>

<div class="header-container header-style-22">
    <div class="header-top">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="logo-header">
                        <?php echo $block->getChildHtml('logo_theme'); ?>
                    </div>
                </div>

                <div class="col-lg-9">
                    <div class="right-top-content">
                        <?php echo $block->getChildHtml('search-header'); ?>

                        <div class="customer-content">
                            <div class="have-dropdown setting-store">
                                <a class="title-icon">
                                    <span class="title-setting"><?php echo __('Setting') ?></span>
                                </a>

                                <div class="dropdown-content">
                                    <?php echo $block->getChildHtml('language-header'); ?>
                                    <?php echo $block->getChildHtml('currency-header'); ?>
                                </div>
                            </div>

                            <div class="have-dropdown account-store">
                                <a class="title-icon">
                                    <span class="title-setting"><?php echo __('Account') ?></span>
                                </a>

                                <div class="dropdown-content">
                                    <?php echo $block->getChildHtml('toplinks-header'); ?>
                                </div>
                            </div>

                            <div class="wishlist-store">
                                <a class="title-icon" href="<?php echo $this->getUrl('wishlist') ?>">
                                    <span class="title-setting"><?php echo __('Wishlist') ?></span>
                                </a>
                            </div>

                            <?php echo $block->getChildHtml('cart-header'); ?>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="header-bottom">
        <div class="container">
            <div class="desktop-menu">
                <div class="large-menu">
                    <?php
                    if ($_config->getGeneral('menu_style') == 'megamenu') {
                        echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('megamenu-horizontal')->toHtml();
                    } else {
                        echo $block->getChildHtml('navigation-header');
                    }
                    ?>
                </div>

                <div class="navigation-mobile-container">
                    <?php echo $block->getChildHtml('navigation.mobile'); ?>
                </div>

                <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('id22-phone-mail')->toHtml(); ?>
            </div>


        </div>
    </div>
</div>
