<?php
/**
 * Copyright © 2016 Ihor Vansach (ihor@magefan.com). All rights reserved.
 * See LICENSE.txt for license details (http://opensource.org/licenses/osl-3.0.php).
 *
 * Glory to Ukraine! Glory to the heroes!
 */
?>
<?php
/**
 * Blog recent posts widget
 *
 * @var $block \Magefan\Blog\Block\Widget\Recent
 */
?>

<?php
$_postCollection   = $block->getPostCollection();
$_config           = $this->helper('Sm\Market\Helper\Data');
$enableLadyLoading = $_config->getAdvanced('enable_ladyloading');
$mediaSrc          = $_config->getMediaUrl();
if ($enableLadyLoading) {
    $imgClass = 'lazyload';
} else {
    $imgClass = '';
}
?>
<?php if ($_postCollection->count()) { ?>
    <div class="latest-post-type2">
        <div class="title-home-page">
            <?php echo $block->escapeHtml($block->getTitle()) ?>
        </div>
        <div class="slider-post-container">
            <div class="owl-carousel slider-post">
                <?php foreach ($_postCollection as $_post) { ?>
                    <?php
                    $_postUrl  = $_post->getPostUrl();
                    $_postName = $block->escapeHtml($_post->getTitle(), null, true);
                    ?>
                    <div class="item item-post">
                        <div class="post-content">
                            <div class="image-blog static-image">
                                <?php if ($featuredImage = $_post->getFeaturedImage()) { ?>
                                    <a href="<?php echo $_postUrl ?>" title="<?php echo $_postName ?>">
                                        <img class="<?php echo $imgClass; ?>"

                                            <?php if ($enableLadyLoading) { ?>
                                                src="<?php echo $mediaSrc . 'lazyloading/blank.png'; ?>"
                                                data-src="<?php echo $featuredImage ?>"
                                            <?php } else { ?>
                                                src="<?php echo $featuredImage ?>"
                                            <?php } ?>

                                             alt="<?php echo $_postName ?>"
                                        />
                                    </a>
                                <?php } else { ?>
                                    <a title="<?php echo $_postName; ?>" href="<?php echo $_postUrl ?>">
                                        <img src="<?php /* @escapeNotVerified */
                                        echo $block->getViewFileUrl('images/post/no_image.jpg') ?>"
                                             alt="<?php echo $_postName ?>"/>
                                    </a>
                                <?php } ?>
                            </div>

                            <div class="info-blog">
                                <h2 class="postTitle">
                                    <a class="post-item-link" href="<?php echo $_postUrl ?>">
                                        <?php echo $_postName; ?>
                                    </a>
                                </h2>

                                <div class="date-comment">
								<span class="date">
									<?php echo $_post->getPublishDate('Y-m-d'); ?>
								</span>
                                </div>

                                <div class="postContent">
                                    <?php
                                    $content    = $block->getShorContent($_post);
                                    $short_text = strip_tags($content);
                                    echo substr($short_text, 0, 120) . '...';
                                    ?>
                                </div>

                                <a class="readmore" title="Read more"
                                   href="<?php echo $_postUrl ?>"><?php echo __('Read more') ?></a>
                            </div>
                        </div>
                    </div>

                <?php } ?>
            </div>
        </div>


        <script type="text/javascript">
            require([
                'jquery',
                'owlcarousel'
            ], function ($) {
                $(".slider-post").owlCarousel({
                    responsive: {
                        0: {
                            items: 1
                        },
                        480: {
                            items: 2
                        },
                        768: {
                            items: 2
                        },
                        992: {
                            items: 3
                        },
                        1200: {
                            items: 3
                        },
                    },
                    autoplay: false,
                    loop: false,
                    nav: true,
                    dots: false,
                    autoplayHoverPause: true,
                    margin: 30
                });
            });
        </script>
    </div>
<?php } ?>