<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/* @var $block \Magento\Catalog\Block\Product\AbstractProduct */
?>

<?php
$_config   = $this->helper('Sm\Market\Helper\Data');
$homeStyle = $_config->getThemeLayout('home_style');
switch ($type = $block->getType()) {
    case 'crosssell-rule':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->hasItems()) {
            $type  = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $items = $block->getItemCollection();

            $showWishlist      = true;
            $showCompare       = true;
            $showCart          = true;
            $templateType      = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description       = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'crosssell':
        /** @var \Magento\Catalog\Block\Product\ProductList\Crosssell $block */
        if ($exist = $block->getItemCount()) {
            $type  = 'crosssell';
            $class = $type;

            $image = 'cart_cross_sell_products';
            $items = $block->getItems();

            $showWishlist      = true;
            $showCompare       = true;
            $showCart          = true;
            $templateType      = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
            $description       = false;
            $canItemsAddToCart = false;
        }
        break;

    case 'other':
        break;
}
?>

<?php if ($exist): ?>
    <div class="crosssell-container">
        <div class="detail-title">
            <span><?php echo __('More Choices:') ?></span>
        </div>

        <div class="crosssell-block category-product products wrapper products-grid">
            <div class="products list items product-items row">
                <?php foreach ($items as $_item): ?>
                    <div class="item product product-item">
                        <div class="product-item-info" data-container="product-grid">
                            <a href="<?php /* @escapeNotVerified */
                            echo $block->getProductUrl($_item) ?>" class="product photo product-item-photo">
                                <?php echo $block->getImage($_item, $image)->toHtml(); ?>
                            </a>

                            <!--LABEL PRODUCT-->
                            <?php
                            $orgprice = (float)$_item->getPrice();
                            $fnPrice  = (float)$_item->getFinalPrice();

                            if ($_config->getAdvanced('show_salelabel')) {
                                if ($fnPrice < $orgprice) { ?>
                                    <div class="label-product label-sale">
											<span class="sale-product-icon">
												<?php echo __('Sale'); ?>
											</span>
                                    </div>
                                <?php }
                            }
                            ?>

                            <?php
                            $now      = date("Y-m-d");
                            $newsFrom = substr($_item->getNewsFromDate(), 0, 10);
                            $newsTo   = substr($_item->getNewsToDate(), 0, 10);


                            if (($newsTo != '' || $newsFrom != '') && $_config->getAdvanced('show_newlabel')) {
                                if (($newsTo != '' && $newsFrom != '' && $now >= $newsFrom && $now <= $newsTo) || ($newsTo == '' && $now >= $newsFrom) || ($newsFrom == '' && $now <= $newsTo)) { ?>
                                    <div class="label-product label-new">
                                        <span class="new-product-icon"><?php echo __('New'); ?></span>
                                    </div>
                                <?php }
                            } ?>
                            <!--END LABEL PRODUCT-->

                            <div class="product details product-item-details">
                                <strong class="product name product-item-name">
                                    <a class="product-item-link"
                                       title="<?php echo $block->escapeHtml($_item->getName()) ?>"
                                       href="<?php /* @escapeNotVerified */
                                       echo $block->getProductUrl($_item) ?>">
                                        <?php echo $block->escapeHtml($_item->getName()) ?>
                                    </a>
                                </strong>

                                <?php echo $block->getReviewsSummaryHtml($_item, $templateType, true) ?>

                                <?php /* @escapeNotVerified */
                                echo $block->getProductPrice($_item); ?>

                                <div class="product-item-inner">
                                    <div class="product actions product-item-actions">
                                        <div class="actions-primary">
                                            <?php if ($_config->getAdvanced('show_addtocart_button')) { ?>
                                                <?php if ($_item->isSaleable()): ?>
                                                    <?php if ($_item->getTypeInstance()->hasRequiredOptions($_item)): ?>
                                                        <button class="action tocart primary"
                                                                data-mage-init='{"redirectUrl": {"url": "<?php /* @escapeNotVerified */
                                                                echo $block->getAddToCartUrl($_item) ?>"}}'
                                                                type="button" title="<?php /* @escapeNotVerified */
                                                        echo __('Add to Cart') ?>">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php else: ?>
                                                        <?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
                                                        $postData             = $postDataHelper->getPostData($block->getAddToCartUrl($_item), ['product' => $_item->getEntityId()])
                                                        ?>
                                                        <button class="action tocart primary"
                                                                data-post='<?php /* @escapeNotVerified */
                                                                echo $postData; ?>' type="button"
                                                                title="<?php /* @escapeNotVerified */
                                                                echo __('Add to Cart') ?>">
														<span><?php /* @escapeNotVerified */
                                                            echo __('Add to Cart') ?></span>
                                                        </button>
                                                    <?php endif; ?>
                                                <?php else: ?>
                                                    <?php if ($_item->getIsSalable()): ?>
                                                        <div class="stock available"><span><?php /* @escapeNotVerified */
                                                                echo __('In stock') ?></span></div>
                                                    <?php else: ?>
                                                        <div class="action tocart primary"><span><?php /* @escapeNotVerified */
                                                                echo __('Out of stock') ?></span></div>
                                                    <?php endif; ?>
                                                <?php endif; ?>
                                            <?php } ?>
                                        </div>

                                        <div class="actions-secondary">
                                            <?php if ($_config->getAdvanced('show_wishlist_button')) { ?>
                                                <?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow()): ?>
                                                    <a href="#" data-post='<?php /* @escapeNotVerified */
                                                    echo $block->getAddToWishlistParams($_item); ?>'
                                                       class="action towishlist btn-action link-wishlist"
                                                       data-action="add-to-wishlist"
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Wish List') ?>">
													<span><?php /* @escapeNotVerified */
                                                        echo __('Add to Wish List') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php } ?>



                                            <?php if ($_config->getAdvanced('show_compare_button')) { ?>
                                                <?php if ($block->getAddToCompareUrl()): ?>
                                                    <?php $compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare'); ?>
                                                    <a href="#" class="action tocompare btn-action link-compare"
                                                       data-post='<?php /* @escapeNotVerified */
                                                       echo $compareHelper->getPostDataParams($_item); ?>'
                                                       data-role="add-to-links"
                                                       title="<?php /* @escapeNotVerified */
                                                       echo __('Add to Compare'); ?>">
													<span><?php /* @escapeNotVerified */
                                                        echo __('Add to Compare') ?></span>
                                                    </a>
                                                <?php endif; ?>
                                            <?php } ?>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php endforeach ?>
            </div>
        </div>
    </div>
<?php endif; ?>
